{% set cctools_version = '1030.6.3' %}
{% set ld64_version = '956.6' %}
{% if llvm_version is not defined %}
{% set llvm_version = "21.1" %}
{% endif %}
{% set clang_exe_version = "19" %}

{% if cross_platform is not defined %}
{% set cross_platform = "osx-64" %}
{% endif %}

package:
  name: cctools-and-ld64
  version: {{ ld64_version }}

source:
  # latest commit from branch {{ cctools_version }}-ld64-{{ ld64_version }}
  - url: https://github.com/tpoechtrager/cctools-port/archive/e5dfc5633cb9060a94d16b8d78a01eb0b3620021.tar.gz
    sha256: 71b56ff5dd5ce4ee4aa70113cae73fc349968518839222b0ba391e06f04dec66
    patches:
      - patches/0001-Don-t-link-with-libc-abi.patch
      - patches/0002-ld64-add-conda-specific-env-vars-to-modify-lib-searc.patch
      - patches/0003-macos-system-dispatch.patch    # [osx]
      - patches/0004-avoid-stripping-out-C-stdlib-too-zealously.patch    # [osx]
      - patches/0005-fix-as-triple.patch
      - patches/0006-Find-sigtool-codesign-first.patch

build:
  number: 4
  skip: True  # [win]
  ignore_run_exports:
    - zlib
  script_env:
    - CLANG_EXE_VERSION={{ clang_exe_version }}

requirements:
  build:
    - clang-{{ clang_exe_version }}   # [linux]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - llvmdev {{ llvm_version }}.*  # [build_platform != target_platform]
    - make
    - sed
  host:
    #- xar
    # We only use the static library from this and only get away with that as it depends on nothing.
    - zlib
    - llvmdev {{ llvm_version }}.*
    - libdispatch   # [linux]
    - libuuid       # [linux]
    - tapi

outputs:
  - name: cctools_impl_{{ cross_platform }}
    version: {{ cctools_version }}
    script: install-cctools-impl.sh
    build:
      string: llvm{{ llvm_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      activate_in_script: True
      ignore_run_exports:
        - zlib
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
        - sed
      host:
        - zlib
        - llvmdev {{ llvm_version }}.*
        - llvm {{ llvm_version }}.*
        - tapi
        - libcxx  # [osx]
        - {{ pin_subpackage("ld64_" + cross_platform, max_pin="x.x") }}
      run:
        - libcxx  # [osx]
        - {{ pin_subpackage("ld64_" + cross_platform, max_pin="x.x") }}
        - llvm-tools {{ llvm_version }}.*
        - sigtool-codesign
      run_constrained:
        - ld64 {{ ld64_version }}.*
        - cctools {{ cctools_version }}.*
        # clang might pull in the wrong cctools otherwise
        - clang {{ llvm_version }}.*
    test:
      commands:
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-ar
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-as
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-ld
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-install_name_tool
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-otool
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-ranlib
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-strip
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-c++filt
        # Check that otool is functioning
        - $PREFIX/bin/{{ cross_macos_machine }}-otool -l $PREFIX/bin/{{ cross_macos_machine }}-otool  # [target_platform == build_platform and target_platform == cross_platform]
        # ... even if PATH is empty
        - unset PATH                                                # [target_platform == build_platform and target_platform == cross_platform]
        - $PREFIX/bin/{{ cross_macos_machine }}-otool --version     # [target_platform == build_platform and target_platform == cross_platform]

    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files

  - name: cctools_{{ cross_platform }}
    version: {{ cctools_version }}
    script: install-activation.sh
    build:
      string: llvm{{ llvm_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
    requirements:
      run:
        - {{ pin_subpackage("ld64_" + cross_platform, exact=True) }}
        - {{ pin_subpackage("cctools_impl_" + cross_platform, exact=True) }}
      run_constrained:
        - cctools {{ cctools_version }}.*
    test:
      commands:
        - test -f $PREFIX/bin/$LD
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Activation scripts for assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files

  - name: ld64_{{ cross_platform }}
    version: {{ ld64_version }}
    script: install-ld64.sh
    build:
      string: llvm{{ llvm_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      activate_in_script: True
      missing_dso_whitelist:
        - /usr/lib/libxar.1.dylib  # [osx]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('cxx') }}
        - autoconf
        - automake
        - make
        - sed
      host:
        - llvm {{ llvm_version }}.*
        - tapi
        - libcxx    # [osx]
        - libdispatch   # [linux]
        - libuuid   # [linux]
      run:
        - {{ pin_compatible("tapi") }}
        - libcxx    # [osx]
        - sigtool-codesign
      run_constrained:
        - ld64 {{ ld64_version }}.*
        - clang {{ llvm_version }}.*
        - cctools {{ cctools_version }}.*
        - cctools_impl_{{ cross_platform }} {{ cctools_version }}.*
    test:
      requires:
        - clang-{{ clang_exe_version }}
      commands:
        - test -f $PREFIX/bin/{{ cross_macos_machine }}-ld
        - echo "int main() {}" > lto.c                                                  # [osx]
        - clang-{{ clang_exe_version }} -c lto.c -o lto.o -flto                         # [osx]
        - $PREFIX/bin/{{ cross_macos_machine }}-ld lto.o -o lto -lSystem -arch x86_64   # [osx]
      downstreams:
        - gfortran_osx-64  # [osx and cross_platform=="osx-64"]
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/ld64/APPLE_LICENSE
      summary: Darwin Mach-O cross linker

  - name: ld64
    version: {{ ld64_version }}
    build:
      string: llvm{{ llvm_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      skip: True   # [cross_platform != target_platform]
    script: install-ld64-symlinks.sh
    requirements:
      host:
        - llvm  {{ llvm_version }}.*
        - {{ pin_subpackage("ld64_" + cross_platform, exact=True) }}
      run:
        - {{ pin_subpackage("ld64_" + cross_platform, exact=True) }}
      run_constrained:
        - cctools {{ cctools_version }}.*
        - cctools_{{ cross_platform }} {{ cctools_version }}.*
    test:
      commands:
        - test -f $PREFIX/bin/ld
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/ld64/APPLE_LICENSE
      summary: Darwin Mach-O native linker

  - name: cctools
    version: {{ cctools_version }}
    script: install-cctools-symlinks.sh
    build:
      string: llvm{{ llvm_version.replace(".", "_") }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      skip: True   # [cross_platform != target_platform]
    requirements:
      host:
        - llvm {{ llvm_version }}.*
        - {{ pin_subpackage("ld64", exact=True) }}
        - {{ pin_subpackage("cctools_impl_" + cross_platform, exact=True) }}
      run:
        - {{ pin_subpackage("ld64", exact=True) }}
        - {{ pin_subpackage("cctools_impl_" + cross_platform, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/bin/as
        - test -f $PREFIX/bin/ranlib
        - test -f $PREFIX/bin/ar
        - test -f $PREFIX/bin/otool
        - test -f $PREFIX/bin/install_name_tool
        - test -f $PREFIX/bin/strip
        - test ! -f $PREFIX/bin/libtool
    about:
      home: https://github.com/tpoechtrager/cctools-port
      license: APSL-2.0
      license_family: Other
      license_file: cctools/APPLE_LICENSE
      summary: Native assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files

about:
  home: https://github.com/tpoechtrager/cctools-port
  license: APSL-2.0
  license_family: Other
  license_file: cctools/APPLE_LICENSE
  summary: Assembler, archiver, ranlib, libtool, otool et al for Darwin Mach-O files. Darwin Mach-O linker.

extra:
  recipe-maintainers:
    - isuruf
    - davidbrochart
    - katietz
    - h-vetinari
