build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
remote_ci_setup:
  - conda-forge-ci-setup=4
  # https://github.com/conda/conda-build/issues/5613
  - conda-build <25
test: native_and_emulated
