MACOSX_DEPLOYMENT_TARGET:
- '10.9'
MACOSX_SDK_VERSION:
- '10.13'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_platform:
- osx-64
cxx_compiler:
- clang_bootstrap
cxx_compiler_version:
- '15'
llvm_version:
- '16.0'
macos_machine:
- x86_64-apple-darwin13.4.0
target_platform:
- osx-64
zip_keys:
- - llvm_version
  - MACOSX_DEPLOYMENT_TARGET
- - macos_machine
  - cross_platform
zlib:
- '1.2'
