# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-11
  strategy:
    matrix:
      osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-64llvm_version17.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-64llvm_version17.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-64llvm_version18.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-64llvm_version18.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-arm64llvm_version17.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-arm64llvm_version17.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
      osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-arm64llvm_version18.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.13cross_platformosx-arm64llvm_version18.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
      osx_64_MACOSX_DEPLOYMENT_TARGET10.9cross_platformosx-64llvm_version16.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.9cross_platformosx-64llvm_version16.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_64_MACOSX_DEPLOYMENT_TARGET10.9cross_platformosx-arm64llvm_version16.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_64_MACOSX_DEPLOYMENT_TARGET10.9cross_platformosx-arm64llvm_version16.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-64llvm_version16.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_arm64_cross_platformosx-64llvm_version16.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-64llvm_version17.0macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_arm64_cross_platformosx-64llvm_version17.0macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-64llvm_version18.1macos_machinex86_64-apple-darwin13.4.0:
        CONFIG: osx_arm64_cross_platformosx-64llvm_version18.1macos_machinex86_64-apple-darwin13.4.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-arm64llvm_version16.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_arm64_cross_platformosx-arm64llvm_version16.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-arm64llvm_version17.0macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_arm64_cross_platformosx-arm64llvm_version17.0macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
      osx_arm64_cross_platformosx-arm64llvm_version18.1macos_machinearm64-apple-darwin20.0.0:
        CONFIG: osx_arm64_cross_platformosx-arm64llvm_version18.1macos_machinearm64-apple-darwin20.0.0
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)